---
- name: Let's start the work
  hosts: '{{var1}}'
  become: yes
  vars_files:
          - newfolder/default.yml
          - newfolder/apache_{{ ansible_os_family }}.yml
  
  tasks:
          - name: Let's install the {{var2}}
            yum:
                    name: '{{var2}}'
                    state: present
            tags:
                    - install

          - name: Copy the index file
            copy:
                    src: newfolder/index.html
                    dest: /var/www/html/
            tags:
                    - install    

          - name: Start the {{var2}}
            systemd:
                    name: '{{var2}}'
                    state: started
                    enabled: yes
            when: ansible_os_family == "RedHat"
            tags:
                    - install

          - name: Start the {{var2}}
            service:
                    name: '{{var2}}'
                    state: started
                    enabled: yes
            when: ansible_os_family == "Debian"
            tags:
                    - install

          - name: Copy the script
            copy:
                    src: '{{pscript}}'
                    dest: /tmp
            tags:
                    - status

          - name: Running the script
            shell: python3 /tmp/'{{pscript}}'
            tags:
                    - status
            register: var3

          - name: Saving in the template
            template:
                    src: sample.txt.j2
                    dest: /tmp/sample.txt
            tags:
                    - status   

          - name: Stop the {{var2}}
            systemd:
                    name: '{{var2}}'
                    state: stopped
            when: ansible_os_family == "RedHat"
            tags:
                    - uninstall

          - name: Stop the {{var2}}
            service:
                    name: '{{var2}}'
                    state: stopped
            when: ansible_os_family == "Debian"
            tags:
                    - uninstall

          - name: Remove the index file
            file:
                    path: /var/www/html/index.html
                    state: absent
            tags:
                    - uninstall        

          - name: Remove the {{var2}}
            yum:
                    name: '{{var2}}'
                    state: absent
            tags:
                    - uninstall     
